### PR TITLE
Add a check to enable or not if there is a DrupalImage

### PR DESCRIPTION
**Pull request by vincentmoulene**
**Problem/Motivation**

- When I have no image in a ckeditor, the ckeditor does not works.
50905335-dfeff780-1422-11e9-9e53-55806ec75c9e

**Proposed resolution**

- Add a check to enable or not the module for the corresponding ckeditor

**Completed tasks**

**Remaining tasks**

- I think is not a good way to have a double foreach (but it's in a big array). May be you now an elegant way to find a value in a big multidimensionnal array when you don't now the corresponding key.

### CODE REVIEW

**Comment by WengerK** [comment]
The issue occure when you enable the module but don't use the button ?

**Comment by vincentmoulene** [comment]
Exactly. 
My case : 3 editors and one without image
Module enabled.

**Comment by WengerK** [comment]
Possible to have a tests which create a new editor & don't assign the button ? To show whitout the fix the JS crash ?

**Comment by WengerK** [comment]
Closed by #fe63fa5

**Pull request closed without merging**
